[book]
authors = ["PROMETHIA"]
language = "en"
multilingual = false
src = "src"
title = "Dependency Injection like Bevy Engine from Scratch"

[output.html]
git-repository-url = "https://github.com/PROMETHIA-27/dependency_injection_like_bevy_from_scratch"
